# Generated by Django 4.0.6 on 2022-07-21 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.IntegerField(default=' ', max_length=50)),
                ('last_name', models.CharField(default=' ', max_length=50)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
